# Generated by Django 6.1.1 on 2026-09-07 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('summer', 'Summer'), ('winter', 'Winter')], max_length=20)),
                ('subcategory', models.CharField(choices=[('cooler', 'Cooler'), ('cooler_spare_parts', 'Cooler Spare Parts'), ('honeycomb', 'Honeycomb / Cooler Grass'), ('table_fan', 'Table Fan'), ('bullet_fan', 'Bullet Fan'), ('stand_fan', 'Stand Fan'), ('ceiling_fan', 'Ceiling Fan'), ('sun_heater', 'Sun Heater'), ('quartz_heater', 'Quartz Heater'), ('immersion_rod', 'Immersion Rod')], max_length=50)),
                ('brand', models.CharField(blank=True, max_length=100)),
                ('model', models.CharField(blank=True, max_length=100)),
                ('size', models.CharField(blank=True, max_length=100)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('description', models.TextField(blank=True)),
                ('features', models.TextField(blank=True)),
                ('available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
