# Generated by Django 6.0.7 on 2026-09-08 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('summer', '☀️ Summer'), ('winter', '❄️ Winter'), ('diwali', '🪔 Diwali'), ('spare_parts', '⚙️ Spare Parts')], max_length=30),
        ),
        migrations.AlterField(
            model_name='product',
            name='subcategory',
            field=models.CharField(choices=[('cooler', 'Cooler'), ('cooler_spare_parts', 'Cooler Spare Parts'), ('honeycomb', 'Honeycomb / Cooler Grass'), ('table_fan', 'Table Fan'), ('bullet_fan', 'Bullet Fan'), ('stand_fan', 'Stand Fan'), ('ceiling_fan', 'Ceiling Fan'), ('sun_heater', 'Sun Heater'), ('quartz_heater', 'Quartz Heater'), ('immersion_rod', 'Immersion Rod'), ('copper_wire_light', 'Copper Wire Light'), ('temple_light', 'Temple Light'), ('multi_function_light', 'Multi Function Light'), ('serial_light', 'Serial / Decorative Light'), ('warm_white_light', 'Warm White Light'), ('multi_colour_light', 'Multi Colour Light'), ('fan_spare_parts', 'Fan Spare Parts'), ('motor', 'Motor'), ('pump', 'Cooler Pump'), ('cooler_motor', 'Cooler Motor'), ('other_spare_parts', 'Other Spare Parts')], max_length=60),
        ),
    ]
